Spliting threshold of fan starting/stopping
Frequently changes of cpu temperatrue will make fan to start/stop in a very short time

The init.d script for pwm-fan is polished too, a simple implement of stop function is made

diff --git a/target/linux/rockchip/armv8/base-files/etc/init.d/pwm-fan b/target/linux/rockchip/armv8/base-files/etc/init.d/pwm-fan
--- a/target/linux/rockchip/armv8/base-files/etc/init.d/pwm-fan
+++ b/target/linux/rockchip/armv8/base-files/etc/init.d/pwm-fan
@@ -1,6 +1,33 @@
 #!/bin/sh /etc/rc.common
 
 START=21
+
+PROG="pwm-fan"
+PROG_PATH="/usr/bin/pwm-fan.sh"
+PID_PATH="/var/run"
+
 start() {
-    /usr/bin/pwm-fan.sh &
+    if [ -e "$PID_PATH/$PROG.pid" ]; then
+        echo "Error! $PROG is currently running!" 1>&2
+        exit 1
+    else
+        $PROG_PATH 2>&1 > /var/log/$PROG & pid=`ps | grep -i $PROG_PATH | grep -v grep | awk '{print $1}'`
+        echo "$PROG started"
+        echo $pid > "$PID_PATH/$PROG.pid"
+    fi
+}
+
+stop() {
+    if [ -e "$PID_PATH/$PROG.pid" ]; then
+        kill `cat $PID_PATH/$PROG.pid`
+        rm -f "$PID_PATH/$PROG.pid"
+    else
+        echo "Error! $PROG is not running!" 1>&2
+        exit 1
+    fi
+}
+
+restart() {
+    stop
+    start
 }
